name: "Setup modules"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ${{ github.workspace }}/node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
    - name: Install packages
      if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      shell: bash
      run: yarn install --frozen-lockfile
