name: "Read builds cache"

runs:
  using: "composite"
  steps:
    - name: Read builds cache
      id: cache-builds-read
      uses: actions/cache/restore@v4
      env:
        cache-name: cache-builds
      with:
        path: |
          ${{ github.workspace }}/react/Icon/icons-sprites.js
          ${{ github.workspace }}/react/palette.js
          ${{ github.workspace }}/transpiled
          ${{ github.workspace }}/dist
          ${{ github.workspace }}/build
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
