#!/bin/bash

if [[ -f "../../.babelrc" ]]; then
  echo "Please temporarily move the .babelrc file for this example to work (see README)."
  echo "$ mv ../../.babelrc ../../.babelrc.bak"
  echo "$ yarn dev"
  echo "$ mv ../../.babelrc.bak ../../.babelrc"
  exit 1
fi

if [[ -f "../../transpiled" ]]; then
  echo "Error: `transpiled` dir is not present."
  echo "Please run `yarn release` in the root directory before running this example."
  exit 1
fi

yarn parcel index.html
